FROM eclipse-temurin:11-jdk-jammy AS builder

RUN set -ex &&         \
    apt-get update &&  \
    apt-get install -y git cmake xz-utils python3 python3-serial ninja-build

RUN curl -L "https://downloads.arduino.cc/arduino-1.8.19-linux64.tar.xz" -o /tmp/arduino-ide.tar.xz
RUN tar -xf /tmp/arduino-ide.tar.xz --directory ~/

RUN cd ~/arduino* && \
    ./install.sh && \
    ./arduino --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json" --save-prefs && \
    ./arduino --install-boards esp32:esp32:2.0.17

RUN git clone --recurse-submodules https://github.com/technyon/Arduino-CMake-Toolchain.git ~/Arduino-CMake-Toolchain

COPY src /usr/src/nuki_hub/src
COPY lib /usr/src/nuki_hub/lib
COPY include /usr/src/nuki_hub/include
COPY CMakeLists.txt /usr/src/nuki_hub

RUN mkdir -p /usr/src/nuki_hub/build

RUN cd /usr/src/nuki_hub/build && \
    echo "# Espressif ESP32 Partition Table" > partitions.csv && \
    echo "# Name, Type, SubType, Offset, Size, Flags" >> partitions.csv && \
    echo "nvs,      data, nvs,     0x9000,  0x5000," >> partitions.csv && \
    echo "otadata,  data, ota,     0xe000,  0x2000," >> partitions.csv && \
    echo "app0,     app,  ota_0,   0x10000, 0x1E0000," >> partitions.csv && \
    echo "app1,     app,  ota_1,   0x1F0000,0x1E0000," >> partitions.csv && \
    echo "spiffs,   data, spiffs,  0x3D0000,0x30000," >> partitions.csv

RUN set -ex && \
    cd /usr/src/nuki_hub/build && \
    touch file_opts && \
    cmake -G Ninja -D CMAKE_TOOLCHAIN_FILE=~/Arduino-CMake-Toolchain/Arduino-toolchain.cmake .. && \
    ninja

FROM builder AS runtime

COPY --from=builder /usr/src/nuki_hub/build/nuki_hub.bin /usr/src/nuki_hub/build/release/nuki_hub.bin
COPY --from=builder /usr/src/nuki_hub/build/nuki_hub.partitions.bin /usr/src/nuki_hub/build/release/nuki_hub.partitions.bin
COPY --from=builder /root/.arduino15/packages/esp32/hardware/esp32/2.0.17/tools/partitions/boot_app0.bin /usr/src/nuki_hub/build/release/boot_app0.bin

CMD ["/bin/bash"]